"""empty message

Revision ID: ab3a89c74009
Revises: 
Create Date: 2022-01-19 10:42:15.243992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab3a89c74009'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resolution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resolution', sa.String(length=100), nullable=False),
    sa.Column('percentage', sa.SMALLINT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resolution')
    # ### end Alembic commands ###
